const { initDatabase } = require('./database');

const sampleJobs = [
  {
    title: "Software Engineering Intern - Summer Vacation Program",
    company: "Atlassian",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 0,
    description: "Join Atlassian's Summer Vacation Program! Work on real projects alongside experienced engineers. Perfect for first-year CS students looking to gain industry experience. This 10-12 week program includes mentorship, training, and the opportunity to contribute to products used by millions.",
    requirements: "Currently enrolled in first or second year Computer Science, Software Engineering, or related degree. Basic programming knowledge in any language. Passion for technology and problem-solving.",
    pay_rate: "$28-32/hour",
    application_url: "https://www.atlassian.com/company/careers/students",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "first_year",
    skills: "Programming fundamentals, Problem solving, Teamwork",
    degree_requirements: "Computer Science, Software Engineering, IT",
    application_deadline: "2024-09-30"
  },
  {
    title: "Software Engineering Intern - Summer Vacation Program",
    company: "Atlassian",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 0,
    description: "Join Atlassian's Summer Vacation Program! Work on real projects alongside experienced engineers. Perfect for first-year CS students looking to gain industry experience. This 10-12 week program includes mentorship, training, and the opportunity to contribute to products used by millions.",
    requirements: "Currently enrolled in first or second year Computer Science, Software Engineering, or related degree. Basic programming knowledge in any language. Passion for technology and problem-solving.",
    pay_rate: "$28-32/hour",
    application_url: "https://www.atlassian.com/company/careers/students",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "first_year",
    skills: "Programming fundamentals, Problem solving, Teamwork",
    degree_requirements: "Computer Science, Software Engineering, IT",
    application_deadline: "2024-09-30"
  },
  {
    title: "IT Support Intern",
    company: "Macquarie Group",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 0,
    description: "First-year friendly IT internship at Macquarie Group. Assist with technical support, learn about enterprise systems, and work with cutting-edge financial technology. Great stepping stone into the tech industry.",
    requirements: "Enrolled in Computer Science, IT, or related field. Strong communication skills. Basic understanding of computer systems. Customer service mindset.",
    pay_rate: "$26-30/hour",
    application_url: "https://www.macquarie.com/careers",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "first_year",
    skills: "IT Support, Communication, Windows, Basic networking",
    degree_requirements: "Computer Science, IT, Information Systems",
    application_deadline: "2024-10-15"
  },
  {
    title: "Web Development Intern",
    company: "Canva",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 0,
    description: "Join Canva's design technology team! Work on frontend features, learn modern web development practices, and contribute to a product loved by millions. Open to first and second-year students with basic HTML/CSS/JavaScript knowledge.",
    requirements: "Basic knowledge of HTML, CSS, and JavaScript. Currently studying Computer Science, Software Engineering, or related. Portfolio of personal projects (even small ones!) is a plus.",
    pay_rate: "$30-35/hour",
    application_url: "https://www.canva.com/careers/students",
    source: "direct",
    flexible_hours: 0,
    remote_option: 1,
    student_level: "first_year",
    skills: "HTML, CSS, JavaScript, React basics",
    degree_requirements: "Computer Science, Software Engineering, IT",
    application_deadline: "2024-09-20"
  },
  {
    title: "Software Developer Intern",
    company: "Commonwealth Bank",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 1,
    description: "CBA's penultimate year internship program for software developers. Work on critical banking systems, cloud infrastructure, and mobile applications. 12-month placement with potential for graduate role. Strong focus on agile development and DevOps practices.",
    requirements: "Penultimate year student in Computer Science, Software Engineering. Proficiency in Java, Python, or C#. Understanding of software development lifecycle. Strong problem-solving skills.",
    pay_rate: "$70,000-75,000 annual pro-rata",
    application_url: "https://www.commbank.com.au/careers",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "penultimate",
    skills: "Java, Python, C#, SQL, Git, Agile, Cloud (AWS/Azure)",
    degree_requirements: "Computer Science, Software Engineering",
    application_deadline: "2024-08-31"
  },
  {
    title: "Data Science Intern",
    company: "Quantium",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 1,
    description: "Work on real-world data science problems in retail, healthcare, and finance. Use Python, machine learning, and statistical analysis to derive insights from big data. Ideal for penultimate year students interested in data analytics and AI.",
    requirements: "Penultimate year in Computer Science, Data Science, Statistics, or related. Strong Python skills. Knowledge of pandas, scikit-learn. Understanding of statistics and machine learning concepts.",
    pay_rate: "$35-40/hour",
    application_url: "https://www.quantium.com/careers",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "penultimate",
    skills: "Python, Pandas, SQL, Machine Learning, Statistics, Data Visualization",
    degree_requirements: "Computer Science, Data Science, Statistics, Mathematics",
    application_deadline: "2024-09-10"
  },
  {
    title: "Full Stack Developer Intern",
    company: "WiseTech Global",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 1,
    description: "Build logistics software used worldwide! Work across the full stack with React, Node.js, and microservices. Perfect for penultimate and final year students with strong coding skills. Includes mentorship from senior developers.",
    requirements: "Penultimate or final year Computer Science/Software Engineering student. Experience with JavaScript/TypeScript, React, Node.js. Understanding of databases and APIs. Passionate about clean code.",
    pay_rate: "$72,000-78,000 annual pro-rata",
    application_url: "https://www.wisetechglobal.com/careers",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "penultimate",
    skills: "JavaScript, TypeScript, React, Node.js, SQL, REST APIs, Docker",
    degree_requirements: "Computer Science, Software Engineering",
    application_deadline: "2024-08-25"
  },
  {
    title: "Cybersecurity Intern",
    company: "Telstra",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 1,
    description: "Join Telstra's cybersecurity team protecting Australia's critical infrastructure. Learn about threat detection, security operations, and incident response. For penultimate/final year students interested in security.",
    requirements: "Penultimate or final year student in Computer Science, Cybersecurity, or IT. Understanding of networking, security principles. Familiarity with Linux. Security+ or similar certification is a bonus.",
    pay_rate: "$68,000-72,000 annual pro-rata",
    application_url: "https://www.telstra.com.au/careers",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "penultimate",
    skills: "Networking, Security, Linux, Python, Security Operations, Threat Analysis",
    degree_requirements: "Computer Science, Cybersecurity, IT",
    application_deadline: "2024-09-05"
  },
  {
    title: "Cloud Engineering Intern",
    company: "AWS (Amazon Web Services)",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 1,
    description: "Work with AWS cloud technologies at scale! Build and deploy cloud solutions, learn about infrastructure as code, and work with distributed systems. For students with strong technical fundamentals.",
    requirements: "Final year Computer Science or Software Engineering student. Strong programming skills (Python, Java, or Go). Understanding of cloud concepts, networking, and distributed systems. AWS certification helpful but not required.",
    pay_rate: "$80,000-90,000 annual pro-rata",
    application_url: "https://www.amazon.jobs/en/teams/university-tech",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "final_year",
    skills: "Python, Java, AWS, Cloud Architecture, Docker, Kubernetes, Terraform",
    degree_requirements: "Computer Science, Software Engineering",
    application_deadline: "2024-08-15"
  },
  {
    title: "Mobile App Developer Intern",
    company: "Afterpay",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 1,
    description: "Build features for the Afterpay mobile app used by millions! Work with iOS or Android native development, collaborate with designers, and ship code to production. Great for penultimate/final year students passionate about mobile.",
    requirements: "Penultimate or final year student. Experience with Swift/iOS or Kotlin/Android. Understanding of mobile design patterns and best practices. Portfolio of mobile projects required.",
    pay_rate: "$35-42/hour",
    application_url: "https://www.afterpay.com/careers",
    source: "direct",
    flexible_hours: 0,
    remote_option: 1,
    student_level: "penultimate",
    skills: "Swift, Kotlin, iOS, Android, Mobile UI/UX, REST APIs, Git",
    degree_requirements: "Computer Science, Software Engineering",
    application_deadline: "2024-09-15"
  },
  {
    title: "DevOps Engineering Intern",
    company: "Atlassian",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 1,
    description: "Learn DevOps practices at scale! Work on CI/CD pipelines, infrastructure automation, and monitoring systems. For penultimate/final year students interested in the intersection of development and operations.",
    requirements: "Penultimate or final year student. Scripting skills (Python, Bash). Basic knowledge of Linux, Docker, and cloud platforms. Interest in automation and infrastructure.",
    pay_rate: "$75,000-82,000 annual pro-rata",
    application_url: "https://www.atlassian.com/company/careers/students",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "penultimate",
    skills: "Linux, Docker, CI/CD, Python, Bash, AWS/GCP, Monitoring, Kubernetes",
    degree_requirements: "Computer Science, Software Engineering, IT",
    application_deadline: "2024-08-30"
  },
  {
    title: "Game Development Intern",
    company: "Wargaming Sydney",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 0,
    description: "Work on AAA game development! Great opportunity for students passionate about gaming to learn game engine development, graphics programming, or gameplay systems. Open to various year levels with relevant skills.",
    requirements: "Computer Science or Software Engineering student. C++ programming skills. Understanding of game development concepts. Portfolio of game projects (personal or academic).",
    pay_rate: "$30-38/hour",
    application_url: "https://wargaming.com/careers",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "any",
    skills: "C++, Game Engines (Unity/Unreal), Mathematics, Graphics Programming",
    degree_requirements: "Computer Science, Software Engineering, Game Development",
    application_deadline: "2024-10-01"
  },
  {
    title: "AI/Machine Learning Intern",
    company: "Google Australia",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 1,
    description: "Work on cutting-edge AI/ML projects at Google! Research and implement machine learning models, work with large datasets, and learn from world-class researchers. Highly competitive program for final year students.",
    requirements: "Final year PhD or advanced Masters student in Computer Science, specializing in AI/ML. Strong publication record or significant project experience. Proficiency in TensorFlow/PyTorch, Python. Strong mathematical background.",
    pay_rate: "$50-60/hour",
    application_url: "https://careers.google.com/students",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "final_year",
    skills: "Python, TensorFlow, PyTorch, Machine Learning, Deep Learning, NLP, Computer Vision",
    degree_requirements: "Computer Science (Masters/PhD), Data Science (Masters/PhD)",
    application_deadline: "2024-07-31"
  },
  {
    title: "Backend Developer Intern",
    company: "Atlassian",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 0,
    description: "Build scalable backend systems for Jira, Confluence, and other Atlassian products. Learn microservices architecture, database design, and API development. Suitable for students with backend development interest.",
    requirements: "Any year Computer Science or Software Engineering student with backend programming experience. Knowledge of Java, Python, or similar. Understanding of databases and REST APIs.",
    pay_rate: "$28-35/hour",
    application_url: "https://www.atlassian.com/company/careers/students",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "any",
    skills: "Java, Python, SQL, REST APIs, Microservices, Docker",
    degree_requirements: "Computer Science, Software Engineering",
    application_deadline: "2024-09-25"
  },
  {
    title: "Frontend Developer Intern",
    company: "Canva",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 1,
    description: "Build beautiful, performant UI for Canva's design platform. Work with React, TypeScript, and modern frontend tooling. For penultimate/final year students with strong frontend skills.",
    requirements: "Penultimate or final year student. Strong JavaScript/TypeScript skills. Experience with React and modern frontend development. Eye for design and UX. Portfolio required.",
    pay_rate: "$75,000-80,000 annual pro-rata",
    application_url: "https://www.canva.com/careers/students",
    source: "direct",
    flexible_hours: 0,
    remote_option: 1,
    student_level: "penultimate",
    skills: "JavaScript, TypeScript, React, CSS, HTML, Frontend Performance, Testing",
    degree_requirements: "Computer Science, Software Engineering",
    application_deadline: "2024-09-01"
  },
  {
    title: "Software Testing & QA Intern",
    company: "Optus",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 0,
    description: "Learn software quality assurance at a major telco! Write automated tests, perform manual testing, and ensure product quality. Great entry point for first-year students into software engineering.",
    requirements: "First or second year Computer Science or IT student. Attention to detail. Basic programming knowledge. Interest in quality assurance and testing.",
    pay_rate: "$25-28/hour",
    application_url: "https://www.optus.com.au/careers",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "first_year",
    skills: "Testing, Test Automation, Selenium, Python, Java, QA processes",
    degree_requirements: "Computer Science, Software Engineering, IT",
    application_deadline: "2024-10-10"
  },
  {
    title: "Network Engineering Intern",
    company: "NBN Co",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 1,
    description: "Work on Australia's national broadband network! Learn about large-scale network infrastructure, routing protocols, and network management. For penultimate/final year students interested in networking.",
    requirements: "Penultimate or final year Computer Science, IT, or Telecommunications student. Understanding of networking fundamentals (TCP/IP, routing, switching). Cisco CCNA certification preferred.",
    pay_rate: "$65,000-70,000 annual pro-rata",
    application_url: "https://www.nbnco.com.au/careers",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "penultimate",
    skills: "Networking, TCP/IP, Routing, Switching, Network Security, Cisco, Python",
    degree_requirements: "Computer Science, IT, Telecommunications, Electrical Engineering",
    application_deadline: "2024-08-20"
  },
  {
    title: "Database Administrator Intern",
    company: "Woolworths Group",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 1,
    description: "Manage databases for Australia's largest retailer! Learn database administration, performance tuning, and data management at scale. For students interested in backend systems and data.",
    requirements: "Penultimate or final year student. Strong SQL skills. Understanding of database concepts (normalization, indexing, transactions). Experience with MySQL, PostgreSQL, or Oracle.",
    pay_rate: "$32-38/hour",
    application_url: "https://www.woolworthsgroup.com.au/careers",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "penultimate",
    skills: "SQL, Database Administration, MySQL, PostgreSQL, Performance Tuning, Backup & Recovery",
    degree_requirements: "Computer Science, IT, Information Systems",
    application_deadline: "2024-09-12"
  },
  {
    title: "Tech Support & Documentation Intern",
    company: "Finder.com.au",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 0,
    description: "Help build and maintain technical documentation and provide tech support for a fast-growing fintech. Great for first-year students who enjoy helping others and technical writing.",
    requirements: "First or second year Computer Science or IT student. Strong communication skills. Basic understanding of web technologies. Detail-oriented with good writing skills.",
    pay_rate: "$24-27/hour",
    application_url: "https://www.finder.com.au/careers",
    source: "direct",
    flexible_hours: 1,
    remote_option: 1,
    student_level: "first_year",
    skills: "Technical Writing, Communication, HTML, CSS, Customer Support",
    degree_requirements: "Computer Science, IT, Information Systems",
    application_deadline: "2024-10-20"
  },
  {
    title: "UI/UX Design Intern (Technical)",
    company: "Atlassian",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 0,
    description: "Bridge design and development! Work on UI/UX design with a technical focus, implement designs in code, and conduct user research. For students interested in the intersection of design and development.",
    requirements: "Computer Science, Software Engineering, or Design student with technical skills. Portfolio showing UI/UX projects. Proficiency in design tools (Figma, Sketch). Basic HTML/CSS/JavaScript knowledge.",
    pay_rate: "$30-36/hour",
    application_url: "https://www.atlassian.com/company/careers/students",
    source: "direct",
    flexible_hours: 0,
    remote_option: 0,
    student_level: "any",
    skills: "UI/UX Design, Figma, HTML, CSS, JavaScript, User Research, Prototyping",
    degree_requirements: "Computer Science, Software Engineering, Design, HCI",
    application_deadline: "2024-09-18"
  },
  {
    title: "Blockchain Developer Intern",
    company: "Independent Reserve",
    location: "Sydney, NSW",
    job_type: "Internship",
    experience_required: 1,
    description: "Work on cryptocurrency exchange platform! Learn about blockchain technology, smart contracts, and financial systems. For penultimate/final year students interested in blockchain and fintech.",
    requirements: "Penultimate or final year Computer Science student. Strong programming skills (Python, JavaScript, or Solidity). Understanding of blockchain concepts. Interest in cryptocurrency and distributed systems.",
    pay_rate: "$38-45/hour",
    application_url: "https://www.independentreserve.com/careers",
    source: "direct",
    flexible_hours: 0,
    remote_option: 1,
    student_level: "penultimate",
    skills: "Python, JavaScript, Solidity, Blockchain, Smart Contracts, Cryptography",
    degree_requirements: "Computer Science, Software Engineering",
    application_deadline: "2024-08-28"
  }
];

function seedDatabase() {
  console.log('Initializing database...');
  const db = initDatabase();
  
  // Clear existing data
  db.exec('DELETE FROM jobs');
  
  // Insert sample jobs
  const insert = db.prepare(`
    INSERT INTO jobs (
      title, company, location, job_type, experience_required,
      description, requirements, pay_rate, application_url, source,
      flexible_hours, remote_option, student_level, skills, degree_requirements, application_deadline
    ) VALUES (
      @title, @company, @location, @job_type, @experience_required,
      @description, @requirements, @pay_rate, @application_url, @source,
      @flexible_hours, @remote_option, @student_level, @skills, @degree_requirements, @application_deadline
    )
  `);
  
  const insertMany = db.transaction((jobs) => {
    for (const job of jobs) {
      insert.run(job);
    }
  });
  
  insertMany(sampleJobs);
  
  console.log(`Seeded ${sampleJobs.length} jobs successfully!`);
  db.close();
}

seedDatabase();
